---
title: "Summary RF metrics"
author: "Karin"
date: "2024-05-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r packages, include=FALSE}
library(dplyr)
library(ggplot2)
library(reshape2)
library(tidyr)
library(stringr)
library(MLmetrics)
library(ComplexHeatmap)
library(viridis)
library(scales)
library(wesanderson)
```


```{r read_files}
base_path = "/Users/forskningskarin/Documents/Courses_workshops_etc/EnvGen_hackathon/Results/Summary17jan2025"

# list and read "Predictions.tsv" files
list_of_prediction_dfs_name = list.files(base_path, pattern = "Predictions.tsv", full.names = TRUE)
list_of_prediction_dfs = lapply(list_of_prediction_dfs_name, read.delim)

# rename the columns
for (i in 1:length(list_of_prediction_dfs)){
  colnames(list_of_prediction_dfs[[i]]) <- str_remove(colnames(list_of_prediction_dfs[[i]]), "Predicted_")
}

list_of_parameters = colnames(list_of_prediction_dfs[[i]])
list_of_parameters = list_of_parameters[!list_of_parameters %in% c("sample_id")]

# list and read "Actual_values.tsv" files
list_of_true_dfs_name = list.files(base_path, pattern = "Actual_values.tsv", full.names = TRUE)
# read the files
list_of_true_dfs = lapply(list_of_true_dfs_name, read.delim)

# list of model names
list_of_true_dfs_name = list.files(base_path, pattern = "Actual_values.tsv", full.names = FALSE)
model_names = str_remove(list_of_true_dfs_name, "_Actual_values.tsv")
```




```{r}
phys_chem_path = '/Users/forskningskarin/Documents/Courses_workshops_etc/EnvGen_hackathon/Results/Summary_physiochemical/physical_chemical_wide_2015_2019_2024-01-17_utf8.txt'

phys_chem = read.delim(phys_chem_path)


phys_chem <- phys_chem %>%
    mutate(institution = case_when(
        grepl("SMHI", dataset_name) ~ "SMHI",
        grepl("UMSC", dataset_name) ~ "UMU",
        grepl("DEEP", dataset_name) ~ "SU",
        TRUE ~ "Other"
    ))

smhi_stations = phys_chem %>%
    filter(institution == "SMHI") %>%
    pull(dataset_name)
```

```{r correlation}
# loop to calculate the correlation for each model
heatmap_df = data.frame()

# set the list of parameters as colnames
for (i in 1:length(list_of_prediction_dfs)){
  
  predictions = list_of_prediction_dfs[[i]]
  true_values = list_of_true_dfs[[i]]
  
  cor_values = c()
  
  # loop to calculate the correlation for each parameter
  for (parameter in list_of_parameters){
    
    filtered_data <- true_values %>%
      filter(!is.na(.data[[parameter]]))
    
    # Get the corresponding predicted values based on the filtered indices
    filtered_predictions <- predictions %>%
      filter(sample_id %in% filtered_data$sample_id)
    
    # Calculate the correlation
    correlation <- MAPE(filtered_predictions[[parameter]], filtered_data[[parameter]])
    
    # Print the correlation
    # print(model_names[i])
    # print(parameter)
    # print(correlation)
    
    cor_values = c(cor_values, correlation)
    
  }
  heatmap_df = rbind(heatmap_df, cor_values)
}

colnames(heatmap_df) = list_of_parameters
rownames(heatmap_df) = model_names
```

```{r heatmap}
# make a heatmap
# convert rownames to a column
heatmap_df$model <- rownames(heatmap_df)

# Melt the dataframe
melted_data <- melt(heatmap_df, id.vars = "model")

# Print the melted dataframe
print(melted_data)

ggplot(melted_data, aes(x = variable, y = model, fill = value)) +
  geom_tile() +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", midpoint = 0.5) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(title = "Correlation between predicted and true values",
       x = "Parameter",
       y = "Model")
```
```{r}
# Data as matrix
mat <- as.matrix(heatmap_df %>% select(-model))

# Annotate the heatmap
# 16S vs 18S, Deep f / tax level, RF / XGB, Type of encoding
heatmap_anno_cols <-
  heatmap_df %>%
    mutate(method = case_when(
      grepl("XGB", model) ~ "XGB",
      grepl("RF", model) ~ "RF")) %>%
    mutate(amplicon_type = case_when(
      grepl("16S", model) ~ "16S",
      grepl("18S", model) ~ "18S")) %>%
    mutate(tax_level = case_when(
      grepl("ASV", model) ~ "ASV",
      grepl("Species", model) ~ "Species",
      grepl("Genus", model) ~ "Genus",
      grepl("Family", model) ~ "Family",
      grepl("Order", model) ~ "Order",
      grepl("Class", model) ~ "Class")) %>%
    mutate(encoding = case_when(
      grepl("VAE_AE", model) ~ "VAE_AE",
      grepl("VAE_CAE", model) ~ "VAE_CAE",
      grepl("VAE_DAE", model) ~ "VAE_DAE",
      grepl("VAE_VAE", model) ~ "VAE_VAE",))

# Convert tax_level to a factor with specified levels
heatmap_anno_cols <- heatmap_anno_cols %>%
  mutate(tax_level = factor(tax_level, levels = c("ASV", "Species", "Genus", "Family", "Order", "Class")))

# Arrange by amplicon_type and then by tax_level
heatmap_anno_cols <- heatmap_anno_cols %>%
  arrange(amplicon_type, tax_level)

# Create row annotations
anno_row <- data.frame(method = heatmap_anno_cols$method,
                      amplicon_type = heatmap_anno_cols$amplicon_type,
                      tax_level = heatmap_anno_cols$tax_level,
                      encoding = heatmap_anno_cols$encoding,
                      stringsAsFactors = FALSE)

# ordered matrix
#mat2<- as.matrix(heatmap_anno_cols %>% select(Longitude:Chl))
#mat3 <- t(scale(t(mat2)))


# Add colours
show_col(viridis_pal(option = "mako", begin = 0.2, end = 0.8)(4))
show_col(viridis_pal(option = "plasma")(4))

anno_colours <- list(
  method = c("RF" = "#5977ff", "XGB" = "#f74747"),
  amplicon_type = c("16S" = "#82ed82", "18S" = "#9e82ed"),
  tax_level = c("ASV" = "#382A54FF", "Species" = "#404589FF", "Genus" = "#36699FFF", "Family" = "#348CA7FF", "Class" = "#3AADACFF", "Order" = "#60CEACFF"),
  encoding = c("VAE_AE" = "#0D0887FF", "VAE_CAE" = "#9C179EFF", "VAE_DAE" = "#ED7953FF", "VAE_VAE" = "#F0F921FF"))

# Pheatmap
# pheatmap(mat,
#          col = circlize::colorRamp2(c(-5, 0, 5), c("blue", "white", "red")),
#          cluster_cols = F, 
#          cluster_rows = F, 
#          show_rownames = F, 
#          annotation_row = anno_row,
#          annotation_colors = anno_colours)


# Complex Heatmap
row_ha <- HeatmapAnnotation(df = anno_row, which = "row", col = anno_colours)
pal <- wes_palette("Zissou1", 6, type = "continuous")

#ComplexHeatmap::pheatmap(mat3, cluster_rows = F, cluster_cols = T, 
#                         show_rownames = F, show_colnames = T, 
#                        color = pal,
#                        column_names_side = c("top"), 
#                        left_annotation = row_ha)#

# ComplexHeatmap::pheatmap(mat, cluster_rows = T, cluster_cols = F,
#                          color = hcl.colors(50, "sunsetdark", rev=F), 
#                          border_color = "black", number_color = "black",
#                          fontsize_number = 9, column_names_side = c("top"),
#                          show_rownames = F, show_colnames = T)
```

```{r}

# Reshape the data frame from wide to long format
long_model_performance <- heatmap_anno_cols %>%
  pivot_longer(cols = c(1:(ncol(heatmap_anno_cols) - 5)),
              names_to = "error_type", 
               values_to = "error_value") %>%
  mutate(tax_level = factor(tax_level, levels = c("ASV", "Species", "Genus", "Family", "Order", "Class")))
  

```


```{r}
# create a box plot based on the taxonomic level (no nitrogen)
filtered_data_no_nitrogen <- long_model_performance %>%
  filter(error_type != 'NO3_NO2')


# Define custom shapes for the error types
custom_shapes <- c(16, 17, 18, 19, 15, 8, 3, 4, 7, 9, 10, 12, 13, 14, 20, 21, 1, 2, 25, 5)



# Filter the data to exclude 'NO3_NO2'
#filtered_data_no_nitrogen <- long_model_performance %>% filter(error_type != 'NO3_NO2')

filtered_data_no_nitrogen = long_model_performance
# Create the plot with transparent boxes and jittered points, using custom shapes
ggplot(filtered_data_no_nitrogen, aes(x = amplicon_type, y = error_value, fill = amplicon_type)) +
  geom_boxplot(outlier.shape = NA, alpha = 0) +  # Make boxes transparent
  geom_jitter(position = position_jitter(width = 0.2), aes(color = error_type, shape = error_type), alpha = 0.6, size = 3) +  # Add jittered points
  scale_shape_manual(values = custom_shapes) +  # Use custom shapes for error types
  theme_minimal() +
  # make log y scale
  scale_y_log10() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(title = "Model performance based on taxonomic level",
       x = "Taxonomic level",
       y = "Error value") +
  facet_wrap(~ tax_level, nrow = 1)

```

```{r}

# Create the plot with transparent boxes and jittered points, using custom shapes
ggplot(filtered_data_no_nitrogen, aes(x = amplicon_type, y = error_value, fill = amplicon_type)) +
  geom_boxplot(outlier.shape = NA, alpha = 0) +  # Make boxes transparent
  geom_jitter(position = position_jitter(width = 0.2), aes(color = error_type, shape = error_type), alpha = 0.6, size = 3) +  # Add jittered points
  scale_shape_manual(values = custom_shapes) +  # Use custom shapes for error types
  theme_minimal() +
  # make log y scale
  scale_y_log10() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(title = "Model performance based on type of encoding",
       x = "Taxonomic level",
       y = "Error value") +
  facet_wrap(~ encoding, nrow = 1)
```

```{r}


# Create the plot with transparent boxes and jittered points, using custom shapes
ggplot(filtered_data_no_nitrogen, aes(x = amplicon_type, y = error_value, fill = amplicon_type)) +
  geom_boxplot(outlier.shape = NA, alpha = 0) +  # Make boxes transparent
  geom_jitter(position = position_jitter(width = 0.2), aes(color = error_type, shape = error_type), alpha = 0.6, size = 3) +  # Add jittered points
  scale_shape_manual(values = custom_shapes) +  # Use custom shapes for error types
  theme_minimal() +
  scale_y_log10() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(title = "Model performance based on type of amplicon",
       x = "Taxonomic level",
       y = "Error value")

```
```{r}
# compare the 16S and 


test_df = long_model_performance %>%
  group_by(amplicon_type) %>%
  summarise(mean_error = mean(error_value), sd_error = sd(error_value))


perc = test_df$mean_error[test_df$amplicon_type == '18S'] / test_df$mean_error[test_df$amplicon_type == '16S']
print(paste('The 18S models have mean MAPE values that are', round(perc, 2), 'times higher than the 16S models'))



```

```{r}

best_model_name = 'RF_withCV_mtryopt_ASV_16S_Abiotic'

actual_values_file_name = paste0(best_model_name, '_Actual_values.tsv')
predictions_file_name = paste0(best_model_name, '_Predictions.tsv')

actual_values = read.delim(paste0(base_path, '/',actual_values_file_name))
predictions = read.delim(paste0(base_path, '/',predictions_file_name))

```


```{r}

# merge the data
predictions_and_actual_data = merge(actual_values, predictions, by = 'sample_id')


```

```{r}
# plot the salinity and predicted salinity
ggplot() +
  geom_point(data = predictions_and_actual_data, aes(x = Salinity, y = Predicted_Salinity), color = 'blue') +
  geom_abline(intercept = 0, slope = 1, color = 'red') +
  labs(title = 'Actual vs Predicted Salinity',
       x = 'Actual Salinity',
       y = 'Predicted Salinity')


# plot the salinity and predicted salinity
ggplot() +
  geom_point(data = predictions_and_actual_data, aes(x = NO3_NO2, y = Predicted_NO3_NO2), color = 'blue') +
  geom_abline(intercept = 0, slope = 1, color = 'red') +
  labs(title = 'Actual vs Predicted NO3 and NO2',
       x = 'Actual NO3_NO2',
       y = 'Predicted NO3_NO2')

# plot the pH and predicted pH
ggplot() +
  geom_point(data = predictions_and_actual_data, aes(x = pH, y = Predicted_pH), color = 'blue') +
  geom_abline(intercept = 0, slope = 1, color = 'red') +
  labs(title = 'Actual vs Predicted pH',
       x = 'Actual pH',
       y = 'Predicted pH')


ggplot() +
  geom_point(data = predictions_and_actual_data, aes(x = Phosphate, y = Predicted_Phosphate), color = 'blue') +
  geom_abline(intercept = 0, slope = 1, color = 'red') +
  labs(title = 'Actual vs Predicted Phosphate',
       x = 'Actual Phosphate',
       y = 'Predicted Phosphate')
```





```{r}
# look at biotic factors

base_path = "/Users/forskningskarin/Documents/Courses_workshops_etc/EnvGen_hackathon/Results/Summary17jan2025/Biotic"


# list and read "Predictions.tsv" files
list_of_prediction_dfs_name = list.files(base_path, pattern = "Predictions.tsv", full.names = TRUE)
list_of_prediction_dfs = lapply(list_of_prediction_dfs_name, read.delim)

# rename the columns
for (i in 1:length(list_of_prediction_dfs)){
  colnames(list_of_prediction_dfs[[i]]) <- str_remove(colnames(list_of_prediction_dfs[[i]]), "Predicted_")
}

list_of_parameters = colnames(list_of_prediction_dfs[[i]])
list_of_parameters = list_of_parameters[!list_of_parameters %in% c("sample_id")]

# list and read "Actual_values.tsv" files
list_of_true_dfs_name = list.files(base_path, pattern = "Actual_values.tsv", full.names = TRUE)
# read the files
list_of_true_dfs = lapply(list_of_true_dfs_name, read.delim)

# list of model names
list_of_true_dfs_name = list.files(base_path, pattern = "Actual_values.tsv", full.names = FALSE)
model_names = str_remove(list_of_true_dfs_name, "_Actual_values.tsv")


```


```{r}
heatmap_df <- data.frame()

# Loop to calculate the correlation for each model
for (i in seq_along(list_of_prediction_dfs)) {
  
  predictions <- list_of_prediction_dfs[[i]]
  true_values <- list_of_true_dfs[[i]]
  
  # Ensure shared columns between predictions and true_values
  common_parameters <- intersect(colnames(predictions), colnames(true_values))
  
  # if sample id is a parameter, remove it
  common_parameters <- common_parameters[common_parameters != 'sample_id']
  cor_values <- numeric(length(common_parameters))
  
  for (j in seq_along(common_parameters)) {
    parameter <- common_parameters[j]
    
    # Filter true values and ensure no NA
    filtered_data <- true_values %>%
      filter(!is.na(.data[[parameter]]))
    
    # Match predictions by sample_id
    filtered_predictions <- predictions %>%
      filter(sample_id %in% filtered_data$sample_id) %>%
      arrange(match(sample_id, filtered_data$sample_id))
    
    # Calculate correlation (replace MAPE with your actual function)
    correlation <- MAPE(filtered_predictions[[parameter]], filtered_data[[parameter]])
    cor_values[j] <- correlation
  }
  
  # Add correlations to heatmap_df
  heatmap_df <- rbind(heatmap_df, cor_values)
}

# Set column and row names
colnames(heatmap_df) <- common_parameters
rownames(heatmap_df) <- model_names

```



